kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: sampleapp-deployment
  labels:
    app: sampleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      run: sampleapp
  template:
    metadata:
      labels:
        run: sampleapp
    spec:
      containers:
      - name: sampleapp-container
        image: 855754041257.dkr.ecr.us-east-2.amazonaws.com/appimage:latest
        ports:
        - containerPort: 8080